upstream spring_servers {
    least_conn;
    server app-1:8080 max_fails=3 fail_timeout=30s;
    server app-2:8080 max_fails=3 fail_timeout=30s;
}
server {
    listen 80;
    # server_name jhkarchive.com www.jhkarchive.com; # 도메인 이름 (또는 EC2 공인 IP), 이거 안하는게 나을듯 ip주소로 오는거 거부함

    location / {
        proxy_pass http://spring_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 주의: Grafana 설정(ini)에서 root_url을 /grafana/로 맞춰야 정상 작동함
    location /grafana/ {
        proxy_pass http://ec2-user-grafana-1:3000/;
        proxy_set_header Host $host;
    }

    # 4. Prometheus 라우팅
    location /prometheus/ {
        proxy_pass http://ec2-user-prometheus-1:9090/;
        proxy_set_header Host $host;
    }
}
