spring:
  application:
    name: budgetTool
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      #cluster 부분은 elasticache 설정
#      cluster:
#        nodes:
#          - ${AWS_REDIS_URL}:${AWS_REDIS_PORT}
#      ssl:
#        enabled: true
      # 커넥션 타임아웃 설정 (네트워크 지연 대비 권장)
      connect-timeout: 2000ms
      timeout: 1000ms
      # docker container conmmunication config
      host: redis
      port: 6379
      ssl:
        enabled: false

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_NAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-milis: 1800000

server:
  port: 8080
  servlet:
    context-path: /budgetTool
    encoding:
      charset: utf-8
      enabled: true

# 에러 페이지 설정
error:
  whitelabel:
    enabled: false
  path: /error
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false

token:
  access: AC_
  refresh: REF_

# mibrometer config
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus